services:
    backend:
        image: silvaomega/exercicios:latest
        ports:
            - 8081:8081
        environment:
            - POSTGRES_DB=example
        networks:
            - spring-postgres
    db:
        image: postgres
        restart: always
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - spring-postgres
        environment:
            - POSTGRES_DB=root
            - POSTGRES_PASSWORD=root
        expose:
            - 5432
        ports:
            - 5432:5432
volumes:
    db-data:
secrets:
    db-password:
        file: db/password.txt
networks:
    spring-postgres: